BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
FLAG_ROWS = 3
FLAG_COLS = 4

START_LOCATION = (0,0)

WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part


FLAG_COLS = 4
flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

BUSHES_COUNT = 20
BUSH_ROWS = 1
BUSH_COLS = 3

#colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (102,187,106)

BACKGROUND_COLOR = GREEN
NIGHT_BACKGROUND_COLOR = BLACK


EXPLOTION_IMAGE_PATH = 'images/explotion.png'
FLAG_IMAGE_PATH = 'images/flag.png'
GRASS_IMAGE_PATH = 'images/grass.png'
GUARD_IMAGE_PATH = 'images/guard.png'
INJURY_IMAGE_PATH = 'images/injury.png'
MINE_IMAGE_PATH = 'images/mine.png'
SNAKE_IMAGE_PATH = 'images/snake.png'
SOLDIER_IMAGE_PATH = 'images/soldier.png'
SOLDIER_NIGHT_IMAGE_PATH = 'images/soldier_night.png'
TELEPORT_IMAGE_PATH = 'images/teleport.png'

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

TEXT_FONT_SIZE = 10
START_TEXT = "Welcome to The Flag game.\nHave Fun!"
START_TEXT_COLOR = WHITE
FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = (89, 89, 89)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

DEFULT_FIELD = {"grass": False, "mine": False}

FREE="free"
BUSH="bush"
MINE="mine"
PLAYER="player"
FLAG="flag"

